# Generated by Django 5.1.2 on 2024-12-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_id', models.IntegerField(blank=True, null=True)),
                ('city_id', models.PositiveSmallIntegerField(default=0)),
                ('city_id_old', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('family', models.CharField(blank=True, max_length=40, null=True)),
                ('cooperation_id', models.PositiveSmallIntegerField()),
                ('personnel_num', models.CharField(blank=True, max_length=40, null=True)),
                ('national_code', models.CharField(blank=True, max_length=15, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=10, null=True)),
                ('father_name', models.CharField(blank=True, max_length=40, null=True)),
                ('sex', models.SmallIntegerField(blank=True, null=True)),
                ('registrar_id', models.IntegerField(blank=True, null=True)),
                ('personnel_img', models.BooleanField(default=False)),
                ('employment_kind_id', models.SmallIntegerField(blank=True, null=True)),
                ('office_post_id', models.SmallIntegerField(blank=True, null=True)),
                ('place_code', models.SmallIntegerField(blank=True, null=True)),
                ('job_id', models.SmallIntegerField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('job_rank_id', models.IntegerField(blank=True, null=True)),
                ('job_type_id', models.IntegerField(blank=True, null=True)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('work_range', models.SmallIntegerField(blank=True, null=True)),
                ('user_in', models.SmallIntegerField(blank=True, null=True)),
                ('post_id', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personnel',
            },
        ),
    ]
