# Generated by Django 5.1.2 on 2024-12-27 00:20

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('menu', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام نقش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=10, verbose_name='وضعیت')),
                ('can_create', models.BooleanField(default=False, verbose_name='ایجاد')),
                ('can_retrieve', models.BooleanField(default=False, verbose_name='مشاهده')),
                ('can_update', models.BooleanField(default=False, verbose_name='ویرایش')),
                ('can_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('can_upload', models.BooleanField(default=False, verbose_name='بارگذاری فایل')),
                ('can_export', models.BooleanField(default=False, verbose_name='خروجی فایل')),
                ('menus', models.ManyToManyField(blank=True, to='menu.menu', verbose_name='دسترسی به منوها')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=100, verbose_name='نام پدر')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], default='M', max_length=1, verbose_name='جنسیت')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('id_number', models.CharField(max_length=10, verbose_name='شماره شناسنامه')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهرستان')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال')], default='active', max_length=10, verbose_name='وضعیت')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='عکس پرسنلی')),
                ('phone_type', models.CharField(choices=[('home', 'منزل'), ('work', 'محل کار'), ('mobile', 'موبایل'), ('fax', 'فکس')], max_length=10, verbose_name='نوع تلفن')),
                ('phone_number', models.CharField(max_length=15, verbose_name='تلفن')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='اولویت')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=128, verbose_name='رمز ورود')),
                ('user_type', models.CharField(choices=[('customer', 'مشتری'), ('admin', 'ادمین')], max_length=20, verbose_name='نوع کاربری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پیوستن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_users', to='user_management.userrole', verbose_name='نوع همکاری')),
                ('work_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_group_users', to='user_management.userrole', verbose_name='گروه کاری')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
