# Generated by Django 5.1.2 on 2025-01-02 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('customer_type', models.PositiveSmallIntegerField(choices=[(1, 'حقیقی'), (2, 'حقوقی')], verbose_name='نوع مشتری')),
                ('clearing_type', models.PositiveSmallIntegerField(choices=[(1, 'نقدی'), (2, 'اعتباری')], verbose_name='نوع تسویه')),
                ('nationality', models.PositiveSmallIntegerField(choices=[(1, 'ایرانی'), (2, 'خارجی')], verbose_name='تابعیت')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('national_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='شناسه ملی')),
                ('passport', models.CharField(blank=True, max_length=10, null=True)),
                ('economy_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='کد اقتصادی')),
                ('name_fa', models.CharField(max_length=40, verbose_name='نام (فارسی)')),
                ('family_fa', models.CharField(max_length=40, verbose_name='نام خانوادگی (فارسی)')),
                ('name_en', models.CharField(blank=True, max_length=40, null=True, verbose_name='نام (انگلیسی)')),
                ('family_en', models.CharField(blank=True, max_length=40, null=True, verbose_name='نام خانوادگی (انگلیسی)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('company_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت (فارسی)')),
                ('company_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت (انگلیسی)')),
                ('mobile', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس شرکت')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='رمز عبور')),
                ('re_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='تکرار رمز عبور')),
                ('email', models.EmailField(blank=True, max_length=170, null=True, verbose_name='پست الکترونیک')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(default=['1403-10-14', '01:07:07'])),
                ('updated_at', models.DateTimeField(default=['1403-10-14', '01:07:07'])),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت ')),
                ('created_at', models.DateTimeField(default=['1403-10-14', '01:07:07'], verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=['1403-10-14', '01:07:07'], verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='PriceAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد')),
                ('price', models.CharField(max_length=10, verbose_name='قیمت(ریال)')),
                ('date', models.DateField(blank=True, default='1403-10-14', null=True, verbose_name='تاریخ ثبت')),
                ('time', models.TimeField(blank=True, default='01:07:07', null=True, verbose_name='زمان ثبت')),
                ('created_at', models.DateTimeField(default=['1403-10-14', '01:07:07'])),
                ('updated_at', models.DateTimeField(default=['1403-10-14', '01:07:07'])),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('analyze_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analyze', verbose_name='آنالیز')),
            ],
            options={
                'db_table': 'price_analysis',
            },
        ),
        migrations.CreateModel(
            name='PriceAnalysisCredit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد')),
                ('price', models.CharField(max_length=10, verbose_name='قیمت(ریال)')),
                ('date', models.DateField(blank=True, default='1403-10-14', null=True, verbose_name='تاریخ ثبت')),
                ('time', models.TimeField(blank=True, default='01:07:07', null=True, verbose_name='زمان ثبت')),
                ('created_at', models.DateTimeField(default=['1403-10-14', '01:07:07'])),
                ('updated_at', models.DateTimeField(default=['1403-10-14', '01:07:07'])),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('analyze_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analyze', verbose_name='آنالیز')),
                ('customers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='مشتریان')),
            ],
            options={
                'db_table': 'price_analysis_credit',
            },
        ),
    ]
