# Generated by Django 5.1.2 on 2024-12-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_paymentmethod_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-11', '23:45:42'], verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-11', '23:45:42'], verbose_name='تاریخ ویرایش'),
        ),
    ]
