# Generated by Django 5.1.2 on 2024-12-31 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_alter_analyze_created_at_alter_analyze_updated_at_and_more'),
        ('customers', '0006_alter_customer_created_at_alter_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-12', '02:31:41']),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-12', '02:31:41']),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-12', '02:31:41'], verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-12', '02:31:41'], verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='analyze_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analyze', verbose_name='آنالیز'),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-12', '02:31:41']),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='time',
            field=models.TimeField(blank=True, default='02:31:41', null=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-12', '02:31:41']),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='analyze_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analyze', verbose_name='آنالیز'),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-12', '02:31:41']),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='time',
            field=models.TimeField(blank=True, default='02:31:41', null=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-12', '02:31:41']),
        ),
    ]
