# Generated by Django 5.1.2 on 2025-01-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_options_alter_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted'),
        ),
        migrations.AddField(
            model_name='priceanalysis',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted'),
        ),
        migrations.AddField(
            model_name='priceanalysiscredit',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates if the record is soft-deleted'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-14', '21:23:40']),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-14', '21:23:40']),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-14', '21:23:40'], verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-14', '21:23:40'], verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-14', '21:23:40']),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='time',
            field=models.TimeField(blank=True, default='21:23:40', null=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-14', '21:23:40']),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-14', '21:23:40']),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='time',
            field=models.TimeField(blank=True, default='21:23:40', null=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-14', '21:23:40']),
        ),
    ]
