# Generated by Django 5.1.2 on 2025-01-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_options_customer_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='status',
            new_name='state',
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='priceanalysis',
            name='state',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='priceanalysiscredit',
            name='state',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-14', '21:28:34']),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-14', '21:28:34']),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-14', '21:28:34'], verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-14', '21:28:34'], verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-14', '21:28:34']),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='time',
            field=models.TimeField(blank=True, default='21:28:34', null=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-14', '21:28:34']),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-14', '21:28:34']),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='time',
            field=models.TimeField(blank=True, default='21:28:34', null=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-14', '21:28:34']),
        ),
    ]
