# Generated by Django 5.1.2 on 2025-01-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_remove_priceanalysis_customers_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30']),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30']),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30'], verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30'], verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30']),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='date',
            field=models.DateField(blank=True, default='1403-10-13', null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='time',
            field=models.TimeField(blank=True, default='18:51:30', null=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30']),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30']),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='date',
            field=models.DateField(blank=True, default='1403-10-13', null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='time',
            field=models.TimeField(blank=True, default='18:51:30', null=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30']),
        ),
    ]
