# Generated by Django 5.1.2 on 2025-01-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customer_created_at_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-13', '19:03:18']),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-13', '19:03:18']),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-13', '19:03:18'], verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-13', '19:03:18'], verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-13', '19:03:18']),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='time',
            field=models.TimeField(blank=True, default='19:03:18', null=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='priceanalysis',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-13', '19:03:18']),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-13', '19:03:18']),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='time',
            field=models.TimeField(blank=True, default='19:03:18', null=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='priceanalysiscredit',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-13', '19:03:18']),
        ),
    ]
