# Generated by Django 5.1.2 on 2024-12-31 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام منو')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='عنوان نمایش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='آدرس لینک')),
            ],
            options={
                'db_table': 'menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زیر منو')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان زیر منو')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='آدرس لینک')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='miscellaneous.menu', verbose_name='منو')),
            ],
            options={
                'db_table': 'submenu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان زیر منو')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='آدرس لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='miscellaneous.submenu', verbose_name='آیتم زیر منو')),
            ],
            options={
                'db_table': 'subitem',
                'ordering': ['submenu__order'],
            },
        ),
    ]
