# Generated by Django 5.1.2 on 2025-01-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
    ]
