# Generated by Django 5.1.2 on 2025-01-02 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyze',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان آنالیز')),
                ('state', models.BooleanField(default=True, verbose_name='وضعیت ')),
                ('created_at', models.DateTimeField(blank=True, default=['1403-10-14', '01:07:07'], null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=['1403-10-14', '01:07:07'], null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'analyze',
            },
        ),
        migrations.CreateModel(
            name='GetAnswer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('state', models.BooleanField(default=True, verbose_name='وضعیت ')),
                ('created_at', models.DateTimeField(default=['1403-10-14', '01:07:07'], verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(default=['1403-10-14', '01:07:07'], verbose_name='زمان بروزرسانی')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حذف')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'get_answers',
            },
        ),
        migrations.CreateModel(
            name='LinkAnalysisPerson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('date', models.DateField(default='1403-10-14', verbose_name='تاریخ ثبت')),
                ('time', models.TimeField(default='01:07:07', verbose_name='زمان ثبت')),
                ('created_at', models.DateTimeField(blank=True, default=['1403-10-14', '01:07:07'], null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=['1403-10-14', '01:07:07'], null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('analyze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_analysis_persons', to='analysis.analyze', verbose_name='آنالیز')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_analysis_persons', to='personnel.personnel', verbose_name='نام فرد')),
            ],
            options={
                'db_table': 'link_analysis_persons',
            },
        ),
    ]
