# Generated by Django 5.1.2 on 2024-12-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getanswer',
            name='status',
            field=models.BooleanField(default=True, help_text='فعال : 1, غیرفعال: 0'),
        ),
    ]
