# Generated by Django 5.1.2 on 2024-12-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_getanswer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getanswer',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-11', '22:11:45'], verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='status',
            field=models.BooleanField(default=True, help_text='فعال : 1, غیرفعال: 0', verbose_name='وضعیت '),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-11', '22:11:45'], verbose_name='زمان بروزرسانی'),
        ),
    ]
