# Generated by Django 5.1.2 on 2025-01-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analyze_created_at_alter_analyze_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='created_at',
            field=models.DateTimeField(blank=True, default=['1403-10-14', '06:31:34'], null=True),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=['1403-10-14', '06:31:34'], null=True),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-14', '06:31:34'], verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-14', '06:31:34'], verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='created_at',
            field=models.DateTimeField(blank=True, default=['1403-10-14', '06:31:34'], null=True),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='time',
            field=models.TimeField(default='06:31:34', verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=['1403-10-14', '06:31:34'], null=True),
        ),
    ]
