# Generated by Django 5.1.2 on 2024-12-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_getanswer_created_at_alter_getanswer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getanswer',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-11', '22:14:35'], verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-11', '22:14:35'], verbose_name='زمان بروزرسانی'),
        ),
    ]
