# Generated by Django 5.1.2 on 2024-12-31 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_getanswer_created_at_and_more'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyze',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='عنوان آنالیز')),
                ('status', models.SmallIntegerField(verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(blank=True, default=['1403-10-11', '22:51:07'], null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=['1403-10-11', '22:51:07'], null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analyze',
            },
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-11', '22:51:07'], verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت '),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-11', '22:51:07'], verbose_name='زمان بروزرسانی'),
        ),
        migrations.CreateModel(
            name='LinkAnalysisPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=['1403-10-11', '22:51:07'], verbose_name='تاریخ ثبت')),
                ('time', models.TimeField(default=['1403-10-11', '22:51:07'], verbose_name='زمان ثبت')),
                ('created_at', models.DateTimeField(blank=True, default=['1403-10-11', '22:51:07'], null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=['1403-10-11', '22:51:07'], null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('analyze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_analysis_persons', to='analysis.analyze', verbose_name='آنالیز')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_analysis_persons', to='personnel.personnel', verbose_name='نام فرد')),
            ],
            options={
                'db_table': 'link_analysis_persons',
            },
        ),
    ]
