# Generated by Django 5.1.2 on 2024-12-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analyze_alter_getanswer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='created_at',
            field=models.DateTimeField(blank=True, default=['1403-10-11', '23:04:21'], null=True),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت '),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=['1403-10-11', '23:04:21'], null=True),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-11', '23:04:21'], verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-11', '23:04:21'], verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='created_at',
            field=models.DateTimeField(blank=True, default=['1403-10-11', '23:04:21'], null=True),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='date',
            field=models.DateField(default=['1403-10-11', '23:04:21'], verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='time',
            field=models.TimeField(default=['1403-10-11', '23:04:21'], verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=['1403-10-11', '23:04:21'], null=True),
        ),
    ]
