# Generated by Django 5.1.2 on 2024-12-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_alter_analyze_created_at_alter_analyze_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='created_at',
            field=models.DateTimeField(blank=True, default=['1403-10-12', '02:34:51'], null=True),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=['1403-10-12', '02:34:51'], null=True),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-12', '02:34:51'], verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-12', '02:34:51'], verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='created_at',
            field=models.DateTimeField(blank=True, default=['1403-10-12', '02:34:51'], null=True),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='time',
            field=models.TimeField(default='02:34:51', verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=['1403-10-12', '02:34:51'], null=True),
        ),
    ]
