# Generated by Django 5.1.2 on 2025-01-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_alter_analyze_created_at_alter_analyze_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='created_at',
            field=models.DateTimeField(blank=True, default=['1403-10-13', '18:51:30'], null=True),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=['1403-10-13', '18:51:30'], null=True),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='created_at',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30'], verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='getanswer',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30'], verbose_name='زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='created_at',
            field=models.DateTimeField(blank=True, default=['1403-10-13', '18:51:30'], null=True),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='date',
            field=models.DateField(default='1403-10-13', verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='time',
            field=models.TimeField(default='18:51:30', verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='linkanalysisperson',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=['1403-10-13', '18:51:30'], null=True),
        ),
    ]
