# Generated by Django 5.1.2 on 2025-01-02 17:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('miscellaneous', '0001_initial'),
        ('personnel', '0002_alter_personnel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('name', models.CharField(max_length=64)),
                ('type', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_name', models.CharField(blank=True, max_length=64, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, default=['1403-10-13', '20:33:32'], null=True)),
                ('updated_at', models.IntegerField(blank=True, default=['1403-10-13', '20:33:32'], null=True)),
            ],
            options={
                'db_table': 'auth_item',
            },
        ),
        migrations.CreateModel(
            name='AuthRule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('name', models.CharField(max_length=64)),
                ('data', models.TextField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, default=['1403-10-13', '20:33:32'], null=True)),
                ('updated_at', models.IntegerField(blank=True, default=['1403-10-13', '20:33:32'], null=True)),
            ],
            options={
                'db_table': 'auth_rule',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('register_date', models.DateTimeField(default=['1403-10-13', '20:33:32'])),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('registrator_id', models.IntegerField(blank=True, null=True)),
                ('accounttype_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('state', models.BooleanField(default=True, help_text='Active: 1, Inactive: 0')),
                ('lastactive', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('personnel_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.personnel')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthAssignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('item_name', models.CharField(max_length=64)),
                ('created_at', models.IntegerField(blank=True, default=['1403-10-13', '20:33:32'], null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_assignment',
            },
        ),
        migrations.CreateModel(
            name='AuthItemChild',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('updated_at', models.DateTimeField(default=['1403-10-13', '20:33:32'])),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_items', to='users.authitem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_items', to='users.authitem')),
            ],
            options={
                'db_table': 'auth_item_child',
            },
        ),
        migrations.CreateModel(
            name='AuthMenu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('item_name', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(default=['1403-10-13', '20:33:32'])),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscellaneous.menu')),
            ],
            options={
                'db_table': 'auth_menu',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('logged_in', 'Logged In'), ('logged_out', 'Logged Out')], max_length=20)),
                ('item_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=['1403-10-13', '20:33:32'])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'useractivity',
                'ordering': ['-date'],
            },
        ),
    ]
