# Generated by Django 5.1.2 on 2025-01-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_authassignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='time',
            field=models.TimeField(default='16:15:40'),
        ),
        migrations.AlterField(
            model_name='authassignment',
            name='created_at',
            field=models.IntegerField(blank=True, default=['1403-10-14', '16:15:40'], null=True),
        ),
        migrations.AlterField(
            model_name='authitem',
            name='created_at',
            field=models.IntegerField(blank=True, default=['1403-10-14', '16:15:40'], null=True),
        ),
        migrations.AlterField(
            model_name='authitem',
            name='updated_at',
            field=models.IntegerField(blank=True, default=['1403-10-14', '16:15:40'], null=True),
        ),
        migrations.AlterField(
            model_name='authitemchild',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-14', '16:15:40']),
        ),
        migrations.AlterField(
            model_name='authmenu',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-14', '16:15:40']),
        ),
        migrations.AlterField(
            model_name='authrule',
            name='created_at',
            field=models.IntegerField(blank=True, default=['1403-10-14', '16:15:40'], null=True),
        ),
        migrations.AlterField(
            model_name='authrule',
            name='updated_at',
            field=models.IntegerField(blank=True, default=['1403-10-14', '16:15:40'], null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='date',
            field=models.DateTimeField(default=['1403-10-14', '16:15:40']),
        ),
    ]
