# Generated by Django 5.1.2 on 2025-01-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_authassignment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authassignment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='personnel',
            new_name='personnel_id',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='authassignment',
            name='created_at',
            field=models.IntegerField(blank=True, default=['1403-10-13', '18:51:30'], null=True),
        ),
        migrations.AlterField(
            model_name='authassignment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='authitem',
            name='created_at',
            field=models.IntegerField(blank=True, default=['1403-10-13', '18:51:30'], null=True),
        ),
        migrations.AlterField(
            model_name='authitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='authitem',
            name='updated_at',
            field=models.IntegerField(blank=True, default=['1403-10-13', '18:51:30'], null=True),
        ),
        migrations.AlterField(
            model_name='authitemchild',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='authitemchild',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30']),
        ),
        migrations.AlterField(
            model_name='authmenu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='authmenu',
            name='updated_at',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30']),
        ),
        migrations.AlterField(
            model_name='authrule',
            name='created_at',
            field=models.IntegerField(blank=True, default=['1403-10-13', '18:51:30'], null=True),
        ),
        migrations.AlterField(
            model_name='authrule',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='authrule',
            name='updated_at',
            field=models.IntegerField(blank=True, default=['1403-10-13', '18:51:30'], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30']),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='date',
            field=models.DateTimeField(default=['1403-10-13', '18:51:30']),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد'),
        ),
    ]
