# Generated by Django 5.1.2 on 2024-12-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='نام زیر منو'),
            preserve_default=False,
        ),
    ]
